server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: admin123
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver